name: Analysis

on:
  pull_request

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and Cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tokei
        run: cargo install tokei

      - name: Run Tokei
        run: tokei . > tokei_output.txt

      - name: Publish code metrics
        run: |
          {
            echo "## Code Metrics"
            echo
            echo '~~~text'
            cat tokei_output.txt
            echo '~~~'
          } >> "$GITHUB_STEP_SUMMARY"
